### ISSUE TITLE
Support React Suspense

### ISSUE THREAD

**Issue by jackjocross** [donavon/splashr#3]
I think React Suspense opens up the possibility of showing the splash screen until your app is loaded, maybe the component could look something like:

```js
const SplashrSuspense = ({ splash, children }) => {
  // Show the fallback immediately on the first render, but then never again
  const [maxDuration, setMaxDuration] = React.useState(0);
  React.useEffect(
    () => {
      setMaxDuration(Infinity);
    },

    []
  );

  return (
    <React.Suspense maxDuration={maxDuration} fallback={splash}>
      {children}
    </React.Suspense>
  );
}; 

export default;
```

Then you could add it to the `Splashr` export:

```js
import SplashrSuspense from './SplashrSuspense';

// ... Splashr code

Splashr.Suspense = SplashrSuspense;

export default Splashr;
```

And then usage would look like:

```js
import Splashr from 'splashr';

const splash = <div className="splash-screen">Welcome to my app</div>;

const App = () => (
  <Splashr.Suspense splash={splash}>
    <div className="app">This is my app.</div>
    {/** other code that suspends! */}
  </Splashr.Suspense>
);
```

I think you would still need to add the transition animation, but let me know what you think!

**Comment by donavon** [comment]
First of all, nice use of 'Infinity'. 😁

I have yet to play with Suspense, but something like this _could_ work. I'd have to make sure of a few things:

1. Both the App and the fallback are available in the DOM simultaneously in order for the fade to work.
1. Suspense supports a minimum durations as well.

I do have the `extend` options already. Maybe some combination of using Suspense to clear `extend` would work. I'll have to play around.

Great idea! Thanks.

**Comment by donavon** [comment]
I have a possible solution in #4. Let me know what you think.

**Comment by donavon** [comment]
now in v0.3.0
